global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'calisota-api'
    static_configs:
      - targets: ['calisota-api:9090']
        labels:
          service: 'calisota'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
